extends: default

ignore: |
  infrastructure/k8s/external-secrets/external-secrets.yaml
  infrastructure/k8s/monitoring/kube-prometheus-stack.yaml
  infrastructure/k8s/monitoring/loki-stack.yaml
  infrastructure/k8s/monitoring/tempo.yaml
  infrastructure/k8s/**/*.sops.yaml
  infrastructure/terraform/

rules:
  line-length:
    max: 200
    level: warning
  document-start: disable
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
